# Generated by Django 3.2.6 on 2021-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_elegirrespuesta_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='answer1',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='answer2',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='answer3',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='answer4',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question',
            field=models.TextField(max_length=50),
        ),
    ]
