# Generated by Django 3.2.6 on 2021-09-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210910_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='correcta',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='correct1',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='correct2',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='correct3',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='correct4',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?'),
        ),
        migrations.DeleteModel(
            name='ElegirRespuesta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
